Lv2-Recsys-01/styl-backend

.gitignore, Dockerfile, docker-compose.yml
=> feat: dockerize fastapi backend app and psql

src/main.py
=> feat: cors middleware

docker-compose.yml, requirements.txt, src/main.py
=> chore: fix for 민호

src/models.py
- User와 Like, Click, Staytime 그리고 Outfit과 Like, Click, Staytime이 1:N 관계라 relationship을 수정했습니다.
- 동호님이 크롤링 한 정보 기반으로 Outfit에 몇 가지 column을 추가했습니다.
- User 테이블의 login_id에 index를 설정하셨는데 이유가 궁금합니다!
+ session_id 추가, 데이터 타입이 배열로 들어오는 column 수정
=> Chore models fix

client/.dockerignore, client/Dockerfile.dev, client/src/hoc/withRouter.jsx, docker-compose.yml
=> feat: 프론트 개발용 도커라이징

docker-compose.yml
=> chore: psql port forwarding change

client/src/components/ImageGridView/imagegridview.css, client/src/components/Login/login.jsx, client/src/hoc/withRouter.jsx, client/src/styles/globalStyle.js
1. healtz -> / 변경
2. Login / SignUp 연결
=> feat front connect backend api

client/src/components/Login/login.jsx, src/router/user_router.py
=> Feat user login

src/models.py, src/router/user_router.py
비 로그인 상태로 저장한 likes -> 로그인 하면 해당 likes들의 user_id를 채워줌
=> feat: inject user id in likes

.gitignore, scripts/insert_outfit.py, scripts/insert_similar.py
1. csv gitignore
2. specify file path more precisley
=> chore: add gitignore for csv files and specify file path more precisley

.gitignore, minho_test/back/main.py, src/main.py, src/router/base.py, src/router/item_router.py, src/router/user_router.py
> commit()은 이미 변경 내용을 데이터베이스에 반영하고 개체가 최신 상태임을 보장합니다. 
> refresh()는 주로 다른 세션에서 개체의 변경 사항이 발생한 경우나 현재 세션에서 개체의 상태가 변경되었지만 데이터베이스에는 아직 반영되지 않은 경우에 유용합니다.
=> chore: remove db.refresh

client/src/components/HeartButton/index.jsx, client/src/components/ImageGridView/index.jsx, client/src/pages/App.jsx, client/src/pages/DetailPage/index.jsx, src/main.py, src/router/item_router.py
=> Feat error fix

src/router/user_router.py
비회원으로 좋아요 누른 아이템이 로그인 한 유저가 이미 좋아요 누른 아이템일 경우 user_id를 업데이트 하지 않음
=> fix: do not update duplicated likes

src/router/item_router.py, src/router/user_router.py
journey에서 random하게 이미지 보여주는 코드 추가
=> add random feed

client/src/components/HeartButton/index.jsx, client/src/components/ImageGridView/imagegridview.css, client/src/components/ImageGridView/index.jsx, client/src/components/Layout/index.jsx, client/src/components/Layout/layout.css, client/src/components/Login/login.css, client/src/components/ToggleRouter/togglerouter.css, client/src/pages/App.jsx, client/src/pages/DetailPage/index.css, client/src/pages/DetailPage/index.jsx, client/src/pages/NotFoundPage/index.jsx, client/src/styles/globalStyle.js, client/src/styles/theme.js
=> feat front-connect-data

client/src/components/Layout/layout.css, client/src/components/Login/login.jsx, client/src/components/Skeleton/skeleton.css, client/src/pages/DetailPage/index.css, client/src/pages/EntryPage/index.css, client/src/pages/EntryPage/index.jsx, src/router/user_router.py, src/schema.py
=> Design final change

client/src/components/HeartButton/index.jsx, client/src/components/ImageGridView/index.jsx, client/src/components/Login/login.jsx, client/src/pages/App.jsx, client/src/pages/DetailPage/index.jsx
=> fix: similart heart

src/router/item_router.py
- csv 파일에 존재하는 10개의 유사한 아이템 중 랜덤하게 3개를 샘플링하도록 수정 -> similar 테이블 업데이트 해야합니다!
=> feat: sampling similar items

.gitignore, client/.gitignore, client/package-lock.json, client/src/pages/EntryPage/index.jsx, client/src/utils/index.js
CRA에선 REACT_APP_ 접사를 붙여야만 된답니다 ㅋㅋㅋ 아 ㅋㅋㅋ
=> chore: add REACT_APP_*

client/src/components/ImageGridView/index.jsx, client/src/components/Layout/index.jsx, client/src/components/Layout/layout.css, client/src/components/Login/login.jsx, client/src/components/MoveBottom/MoveBottom.css, client/src/components/MoveBottom/index.jsx, client/src/components/MoveToTop/MoveToTop.css, client/src/components/MoveToTop/index.jsx, client/src/components/ToggleRouter/index.jsx, client/src/components/ToggleRouter/togglerouter.css, client/src/hoc/withRouter.jsx, client/src/pages/DetailPage/index.css, client/src/pages/DetailPage/index.jsx, client/src/pages/Journey/index.jsx, client/src/pages/Journey/journey.css, client/src/pages/MyPage/index.jsx, client/src/pages/MyPage/mypage.css, client/src/pages/NotFoundPage/index.jsx, src/router/item_router.py
아래 문제를 해결하기 위해서 디자인을 수정하였습니다.
- journey / collection 선택 버튼이 페이지 최상단으로 가야지만 보임.
- 핸드폰 기종에 따라 similar style이 스크롤 하지 않으면 안 보이는 경우가 있음.
- up down button 수정 -> 추후에 남, 녀 기능과 바텀에 툴 박스 추가하여 관리해보겠습니다!
-> 터치 영역 제한해서 버튼 크기 제외하고 터치 잘됨!
- fallback image 추가
- detail 페이지 내에 404 에러 추가
- collection에서 패치 에러 수정 -> collections API 수정
logout 클릭시 -> 이미 로그인 되어있습니다! 라는 notification이 실행될 때가 있음.
--> useEffect에 파라미터 추가하였으나 이유를 모르겠음.
logout 후에도 유저 이름과 상단 headr가 바뀌지 않는 문제
--> useEffect에 cookie가 업데이트 될때마다 상태 업데이트 적용했으나 브라우저의 문제인지 확인 필요.
=> Fix design main page

client/Dockerfile.prod, client/src/styles/globalStyle.js, scripts/insert_outfit_prod.py, scripts/insert_similar_prod.py
=> chore: prod db data inject

client/src/components/Layout/index.jsx, client/src/hoc/withRouter.jsx, client/src/pages/Journey/index.jsx
prevent re-render children in layout comp
=> chore: render only once in layout and remove unused heathlz check

crawling_code/1_href.py, crawling_code/2_imgcrawl.py, crawling_code/3_add_s3url.py, crawling_code/4_infocrawl.py
=> crawling code
